### ISSUE TITLE
Add articles to cite

### ISSUE THREAD

**Issue by odarbelaeze** [coreofscience/sap.coreofscience.com#13]
Add articles to cite in the footer.

@srobledog which ones do we cite nowadays.

**Comment by jdalzatec** [comment]
https://revistas.unal.edu.co/index.php/ingeinv/article/view/77718/74279
https://revistas.udistrital.edu.co/index.php/vinculos/article/download/9664/10837
http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S1794-24702016000100010
